# ==============================================================================
# Basic (Non-Optimized) Dockerfile
# ==============================================================================
FROM ruby:3.3.0

WORKDIR /app

# Copy everything
COPY . .

# Install gems
RUN bundle install

EXPOSE 4567

CMD ["ruby", "app.rb"]
