# ==============================================================================
# Basic (Non-Optimized) Dockerfile
# ==============================================================================
FROM ruby:3.3.0

WORKDIR /app

# Copy everything
COPY . .

# Install gems
RUN bundle install

EXPOSE 9292

CMD ["bundle", "exec", "rackup", "-p", "9292"]
